import { type CaseStudy, m, h, h3, lede, p, small, list, img, gallery, stats, cta, callout, cards, feature } from '../lib/blocks';

const cs: CaseStudy = {
  slug: 'cloudflare',
  eyebrow: 'PERSONAL PROJECT',
  title: 'Cloudflare R2 Object Storage Redesign',
  metaTitle: 'Cloudflare R2 Redesign',
  description: "Redesigned R2's configuration, management, and monitoring flows. Two of the gaps identified have since been shipped independently.",
  meta: [
    ['Role', 'Sole designer, Mar 2026'],
    ['Team', '1 Designer'],
    ['Skills', 'User Research, Design System, Prototyping'],
  ],
  cover: [m('ynF3JX3AYbXmF5u4ZKwl04aGc.png')],
  accent: '#E4691E',
  accentSoft: '#FCE3CF',
  coverBg: 'linear-gradient(#fdc07c 0%, #ffa07d 100%)',
  coverContain: true,
  sections: [
    {
      id: 'overview',
      label: 'Overview',
      blocks: [
        callout(
          'Update',
          'This study examined the dashboard in March 2026.',
          'Cloudflare has since introduced bulk emptying and folder deletion. The original exploration is retained here, with subsequent product changes noted.',
        ),
        h('Opportunity'),
        lede("R2's core strengths (zero egress fees, S3 compatibility, and deep platform integration) create an opportunity to make the dashboard as strong as the infrastructure behind it."),
        stats([
          ['44,000 users', 'Source: Cloudflare Q2 2023 Earnings Call (August 2023)'],
          ['&gt; 13 PB of user data', 'Source: Cloudflare Q2 2023 Earnings Call (August 2023)'],
          ['&gt; 3 community-built alternatives', 'that exist because the official dashboard falls short'],
        ]),
        h('Design Solution'),
        p('<strong>The redesign addresses three phases: configuration, management, and monitoring. </strong>Internal configuration (connecting Workers and Queues to a bucket) and external configuration (setting up S3 API tokens for non-Cloudflare applications) are separate workflows with different pain points, so I addressed them independently.', 'md'),
        cta('Jump to Prototype', 'https://www.figma.com/proto/LnCTzffEiISiq0pprH4rN6/Cloudflare-R2-Object-Storage-Redesign?node-id=70-801&t=LCoksWLXe9K4CA6H-1&scaling=scale-down-width&content-scaling=fixed&page-id=63%3A247&starting-point-node-id=70%3A801&show-proto-sidebar=1'),
      ],
    },
    {
      id: 'empathize',
      label: 'Empathize',
      blocks: [
        h('Why I Redesigned R2'),
        p('I started using R2 as additional cloud storage alongside Google Drive for my data. With 10 GB of free storage, it was a no-brainer to have extra space at no cost. But as I used the dashboard, I kept running into friction that felt unnecessary for a product this strong underneath.'),
        p("That made me curious.<strong> If I'm hitting these walls as someone with a simple use case, what does the experience look like for developers building real applications on top of R2?</strong> I wanted to understand whether my frustrations were personal or structural, and whether there was a design opportunity worth pursuing for Cloudflare's core audience."),
        h('Competitive Analysis'),
        p("First, I conducted a competitive analysis to understand existing solutions. For this, I analyzed popular platforms such as Amazon S3, Google CS, and Backblaze B2 against Cloudflare's R2."),
        gallery(['IVrPyYYRJLjhPvlS4eSOwn52NaE.png', 'dUwbvv6u6jFTHPAMxvRVVm3zjM.png', 'rdJoAbUz5W5JY800YfSnkWN6Y78.png', '9uBbVl51RJXMQ6qhyQ60x39Uo.png'], { cols: 4, frame: 'soft' }),
        p('Some insights include:'),
        list([
          "<strong>R2's dashboard is</strong> <strong>missing foundational interactions</strong> such as one-click bucket deletion, folder downloads, and discoverable API token creation. Their absence is what drives community-built alternatives.",
          '<strong>Every competitor offers</strong> <strong>better analytics and cost visibility than R2. </strong>R2\'s "Class A and Class B Operations" labels with no trends or billing context represent the widest gap in the competitive set.',
          "<strong>No competitor surfaces the</strong> <strong>relationship between storage and compute within the storage dashboard.</strong> R2's integration with Workers, Queues, and Workflows makes it uniquely positioned to be the first.",
        ]),
        h('Interviews'),
        lede('I conducted semi-structured interviews with 4 users to understand their daily workflows, dashboard usage patterns, and friction points.'),
        img('EDfAP8bTFuMCt3cCBqfGA9T7SP4.jpg', { wide: true }),
        cta('See User Interview Guide and Process', 'https://docs.google.com/document/d/1veHnNbCoFFW7A9vTFT5cRXVJkFSbyDrYJQDqJ-6DqYY/edit?usp=sharing'),
      ],
    },
    {
      id: 'define',
      label: 'Define',
      blocks: [
        h('Personas'),
        p("Through four interviews, three behavioral personas emerged. <strong>This redesign targets the two personas who represent Cloudflare's core R2 user base - developers who build on R2 and administrators who manage it. </strong>", 'md'),
        gallery(['ah6Xf97OKA9xBM9n64Z5qtdWmQg.jpg', 'yLHVdvapLHy1NeiXIk5N40FOF8.jpg'], { cols: 2 }),
        p('Analyzing interview data across the two target personas. I found that pain points clustered naturally into three phases: configuration, management, and monitoring. I began mapping them.'),
        h('Mapping the Pain Points'),
        h3('Configuration'),
        lede('Connecting a bucket to Workers and Queues required leaving R2 entirely, with no way to verify the connection.'),
        img('WgCbjKzHjiwauZbYEdrJmoKdl7Q.jpg'),
        p('Setting up an event-driven pipeline, where a bucket change triggers a notification to a queue, and a Worker processes it, <strong>requires four steps across three separate dashboard sections.</strong> The flow demands two full context switches out of R2 to complete what is conceptually a single configuration task, with <strong>no way to verify the full pipeline is connected from any one place.</strong>'),
        img('sudZxkOuimVHarWvtdxTiwKIfoc.jpg'),
        p("Binding a Worker to a bucket so it can read from or write to it is a shorter flow. The friction here isn't the number of steps, but the lack of reverse visibility. <strong>Once the binding is created from the Workers side, the bucket itself has no record of the connection. </strong>Developers must check each Worker individually to find which ones are bound to a given bucket."),
        lede('External configuration split the endpoint from its token and buried the secure bucket-scoped tokens where no one could find it.'),
        img('gwd84tZNvsOf3CHmMADJctg6nA.jpg'),
        p("Connecting R2 to a non-Cloudflare application requires two pieces of information: an S3-compatible endpoint and an authentication token. Both exist on separate pages, one on the settings tab of the bucket and the other on the homepage. Once they do reach the token creation flow, <strong>a more secure bucket-scoped option exists, but it's buried so deeply that two of four developers had no idea it was there.</strong>"),
        h3('Bucket Management'),
        p('Unlike configuration, where friction comes from navigating between disconnected pages, management friction comes from within the bucket itself. Users land in the right place but <strong>find basic tools missing.</strong>'),
        img('vrlXDHVMFZ6k5HGO4OudcarBBOc.jpg', { caption: 'Bucket Management Pain Points - HomePage' }),
        img('jaucYG0tkRPP0Yxyiy98VGTfEB8.jpg', { caption: 'Bucket Management Pain Points - Bucket' }),
        h3('Analytics and Monitoring'),
        lede('Monitoring spoke a language no one understood, showed numbers without trends, and offered no account-wide view.'),
        p("Users return to the R2 dashboard primarily for one reason:<strong> </strong>to understand what their storage is doing and what it's costing them.<strong> </strong>The current analytics experience fails on both counts."),
        list([
          '"Class A and Class B Operations" is internal Cloudflare terminology that even engineers don\'t understand. The vocabulary creates a translation burden every time a developer checks their dashboard.',
          "<strong>Data is presented as static numbers. </strong>There are no trends or time-series charts for R2 as a whole. Developers don't want a snapshot; they want a trajectory.",
          '<strong>Deeper analytics exist per bucket, but not for R2 as a whole.</strong> An administrator managing multiple buckets has no single view to understand overall storage health, compare bucket activity, or identify which buckets are driving the most usage.',
        ]),
        h('Design Goals'),
        cards(
          [
            { img: 'Fn2fGJ6uoe9bJooiMcmTo9gBck.jpg', title: 'Reduce internal configuration steps', html: 'Reduce internal configuration steps, currently scattered across three separate dashboard sections.' },
            { img: 'PfY4jWqw2rBGvI6q8LxIjCKQw.jpg', title: 'Make S3 credentials and per-bucket token creation easy to find', html: 'Surface the right links and labels.' },
            { img: 'HmFCeblpCm7SzpCgHFrf8Yjfg.jpg', title: 'Fix foundational interactions', html: 'These include bucket deletion, folder downloads, visible URIs, and removing low-value clutter.' },
            { img: 'ySz4SWCgEuPuPs3PvYY04HQJVYU.jpg', title: 'Replace opaque terminology with plain language', html: 'Replace "Class A and Class B operations" with simpler language that users can easily comprehend.' },
            { img: 'YSEkGtGxXygwk0F5c8YGSb72qc.jpg', title: 'Surface analytics with time-series trends in a detailed analytics view', html: 'A separate detailed analytics view can support both developer debugging and administrative reporting.' },
            { img: 'WiZEDsRPJVHkrObAdvvQ0TEah5E.jpg', title: 'Show which compute services depend on each bucket', html: "No competitor solves this, and Cloudflare's unified platform makes it uniquely positioned to be the first." },
          ],
          { cols: 3, variant: 'plain' },
        ),
      ],
    },
    {
      id: 'ideate',
      label: 'Ideate',
      blocks: [
        h('Internal Configuration'),
        lede('I condensed four steps into two by surfacing integrations inside the bucket.'),
        img('HidTdRa7ANxckQkjLgegX1Htik.jpg'),
        p('The current internal configuration flow requires four steps across three dashboard sections to set up a single event pipeline. <strong>Looking at how Cloudflare already handles this on the Workers side, I asked myself, why doesn’t the bucket have the same?</strong> The proposed flow condenses four steps into two. This raised three decisions I needed to work through:'),
        list(["<strong>Should bucket integrations be a separate tab or inline on the bucket page?</strong> One developer noted that integrations aren't something you check daily. So, I opted for a dedicated tab to keep connections accessible without cluttering the primary workspace."], true),
        img('Bzurjtq26LcmgkGSyO6oOLiI6UM.jpg', { caption: 'Separate tab vs. inline on the bucket page' }),
        list([
          "<strong>Should Queue connections and Worker bindings be shown in separate views or together?</strong> I chose together. They represent different directions of the same relationship with the bucket, and separating them would force developers to check two places to understand a bucket's full dependency.",
          '<strong>Finally, how to visualize the connections? </strong>A node-based diagram with directional labels, i.e., "Reads/Writes" for Workers and "Notifications" for Queues, communicates both the existence and the nature of each connection at a glance.',
        ]),
        img('D8Mj6D7IrAziCVyRCrNil9l4lE.jpg'),
        h('External Configuration (S3 API token connections)'),
        img('5mrUEYppyJ1F9lFDkEXqgOJ09w.jpg'),
        p('My first instinct was to bring per-bucket token creation directly into the bucket homepage. But that conflicts with a real technical constraint. Administrators need centralized token management on the homepage to oversee all credentials in one place. Instead, I focused on three targeted changes:'),
        list([
          '<strong>Surfacing the S3 API endpoint </strong>directly on the bucket page rather than inside settings.',
          '<strong>Adding a shortcut link to the token creation flow</strong> on that same bucket page, with the per-bucket option highlighted.',
          '<strong>Make per-bucket token creation easy to find. </strong>The per-bucket token option already existed, but the UI presented it as plain-text radio buttons. The change was simple: <strong>replacing flat radio buttons with cards and bold labels. </strong>',
        ]),
        img('gvC62bM3UB1KKcNucYCZzDbuS88.jpg'),
        h('Management'),
        p('Management required fixing what should have been there from the start. <strong>The changes were direct responses to interview data, such as one-click bucket deletion replacing the manual empty-then-delete flow.</strong> I also added a Requests column with inline sparklines, turning a static table into one that immediately answers which buckets are active.'),
        h('Analytics and Monitoring'),
        list(['<strong>Add parenthetical translations to "Class A/B Operations."</strong><br><br>My first instinct was to replace "Class A/B" with "Reads/Writes" entirely. But Class A includes writes, lists, and copies, not just writes. Instead, I kept the billing terms and added parenthetical translations.']),
        gallery(['X0xZsaG4ay0wrDS9K0KhSUHDc.jpg', 'csEDEwbynLWgcVEg3KKy0deu5gE.jpg'], { cols: 2 }),
        list(['<strong>Replace static numbers with time-series charts in a separate detailed analytics view</strong><br><br>Currently, there is no account-level view at all. Administrators had to check each bucket individually. I designed a detailed account-level analytics view and added a dropdown to toggle between all buckets and individual ones.']),
        img('iaZFTmw1LjJ6sFQCiaDCjYl5wOU.jpg', { caption: 'Detailed Analytics View Wireframe' }),
      ],
    },
    {
      id: 'prototype',
      label: 'Prototype',
      blocks: [
        feature({
          kicker: '[WORKFLOW 1]',
          title: 'Internal Configuration',
          html: 'A new Integrations tab surfaces connected Workers, Queues, and other compute services with directional labels, a first across any storage dashboard. There is also an option to create a new queue inline if none exists.',
          media: ['xVY62d93p5rA2uqmmKmIQwjR8I.gif'],
        }),
        feature({
          kicker: '[WORKFLOW 2]',
          title: 'External Configuration',
          html: 'S3 endpoint and token links persist across all bucket tabs, eliminating the current scattered navigation that splits one task across three pages. The redesign also makes per-bucket token creation easily accessible.',
          media: ['0JYHrpqh8iEliclxggLD75ZEjk0.gif'],
        }),
        feature({
          kicker: '[WORKFLOW 3]',
          title: 'Management',
          html: 'One-click bucket deletion replaces the current flow of manually emptying every object first. Sparklines per bucket show activity trends at a glance.',
          media: ['aOQ6T1UV764GiQaZId5sGFokWHg.gif'],
        }),
        feature({
          kicker: '[WORKFLOW 4]',
          title: 'Monitoring',
          html: 'R2 currently offers no account-wide analytics. This redesign introduces time-series charts, translates Class A/B into plain language, adds storage class distribution and request breakdown by bucket, and links directly to R2 pricing.',
          media: ['lR8M0Y29rJGG4GIE3nmmHsmo08.jpg'],
        }),
      ],
    },
    {
      id: 'reflection',
      label: 'Reflection',
      blocks: [
        h('Reflection'),
        list([
          '<strong>Design decisions must be rooted in data before any screen is opened.</strong> Every decision in this project (from keeping Class A/B labels to choosing a separate tab over inline integrations) traced back to an interview quote, a competitive finding, or a technical constraint. Once those decisions were locked, prototyping was easy.',
          "<strong>Real-world product redesign teaches you to design around constraints, not in spite of them.</strong><strong> </strong>I couldn't move token management into bucket settings because administrators need centralized access. I couldn't surface billing totals because that system lives outside R2 by platform-wide design. Working within these boundaries forced more thoughtful solutions.",
          "<strong>The most impactful design opportunity wasn't fixing what's broken, it was building what no one has. </strong>Cross-service visibility between storage and compute doesn't exist in any competitor's dashboard. That insight came not from asking developers what they wanted, but from observing what they had to do to get information the dashboard should have provided.",
        ], true),
      ],
    },
  ],
};

export default cs;
