import { type CaseStudy, m, h, lede, p, list, img, gallery, stats, cards, feature, timeline } from '../lib/blocks';

const cs: CaseStudy = {
  slug: 'csbs',
  eyebrow: 'UX DESIGN INTERN, CSBS',
  title: 'NMLS Resource Center Redesign',
  metaTitle: 'NMLS Resource Center Redesign',
  description: '50% reduction in navigation time by redesigning the Resource Center for the Nationwide Multistate Licensing System (NMLS).',
  meta: [
    ['Role', 'UX Designer, May - Dec 2025'],
    ['Team', '1 Designer, 1 Research Lead, 1 PM'],
    ['Skills', 'User Research, Journey Mapping, Competitive Analysis, Presentation'],
  ],
  cover: [m('hc5LSNViBiB98sAACx272BNZYw.gif')],
  accent: '#3F6FA3',
  accentSoft: '#DCE6F1',
  coverBg: 'linear-gradient(#4778a9 0%, #4a7aab 100%)',
  coverContain: true,
  sections: [
    {
      id: 'overview',
      label: 'Overview',
      blocks: [
        h('Context'),
        lede('<mark>CSBS</mark> is the nationwide organization of banking regulators from all 50 states and U.S. territories.'),
        p('The Nationwide Multistate Licensing System (NMLS) is the <strong>system of record for financial services licensing or registration in 67 state and territorial agencies.</strong>', 'md'),
        h('Problem'),
        lede('Small companies face unique challenges in navigating NMLS licensing compared to larger institutions. Without dedicated staff, they often <mark>rely heavily on the call center</mark> for support.'),
        p('In 2023, the call center received <strong>320,000 calls</strong> from MLOs struggling to complete their licenses, with an <strong>average cost of $9.70 per call</strong>. The scope of this project was to shed light on their overall experience (especially in relation to larger companies), identify specific problems and areas for improvement, and offer potential recommendations to enhance on-demand self-service support.'),
        h('Timeline (for Summer Internship)'),
        timeline([
          ['Onboarding', ''],
          ['Week 2', 'Self-walkthrough<br>Hypothesis Map'],
          ['Week 3', 'Formal Interview Guide<br>for Call Center Interviews'],
          ['Week 4', 'Call Center<br>Interviews'],
          ['Week 5', 'Call Center<br>Interviews Analysis'],
          ['Week 6', 'ServiceNow Quant.<br>Data Analysis'],
          ['Week 7', 'Refine<br>Hypothesis Map'],
          ['Week 8', 'User Interviews'],
          ['Week 9', 'User Interviews<br>Analysis'],
          ['Week 10', 'Finalize User Journey Maps<br>+ handoff'],
        ]),
        h('Scoping'),
        p('The NMLS Resource Center is the official <strong>gateway to the Nationwide Multistate Licensing System &amp; Registry (NMLS)</strong> and provides users with resources, guidance, news, and updates.'),
        img('0NxDsXYd3Emz4a15bzaYYrGgqpc.jpg', { caption: 'NMLS Resource Center (Before Redesign)', frame: 'bare' }),
        p('To keep the effort focused and impactful, we prioritized the redesign around <strong>six core NMLS workflows</strong>. The goal was to simplify navigation and reduce dependency on support calls. These high-priority workflows included:'),
        cards(
          [
            { title: '👤 Account Creation', html: 'Initial setup process for registering a company on the NMLS platform.' },
            { title: '📑 MU1 Filing', html: 'Primary form for companies to apply for licenses.' },
            { title: '✍ MU2 Attestation', html: 'Form required for persons identified as a Control Person or Qualifying Individual (QI).' },
            { title: '📊 Financial Statements', html: 'Electronically submit financial statements to satisfy state agency requirements.' },
            { title: '💲 Form Payments', html: 'Submitting the required fees associated with NMLS filings and license applications.' },
            { title: '⚙️ Account Management', html: 'Managing updates like amendments and Advance Change Notices (ACN).' },
          ],
          { cols: 3, variant: 'plain' },
        ),
        h('Why This Project Matters'),
        cards(
          [
            { img: 'Agm0WamahbMGSZMFlSQG9IOdzA.png', title: 'Reduce call center reliance and costs', html: 'Identifying specific user pain points could improve the user experience for small companies and reduce reliance on the call center.' },
            { img: 'SlhGZxMrkkE0zRF9rwiJZl6SZXs.png', title: "Understand small company user's experiences", html: 'Currently, small companies are underrepresented because most input comes from conferences dominated by large firms.' },
            { img: 'oiVRCFMvswJcgZghEOiH9ZLdrFg.png', title: 'Improve self-service support for NMLS', html: 'Real data helped identify improvements for the new NMLS Resource Center, released in September 2025.' },
          ],
          { cols: 3, variant: 'icon' },
        ),
      ],
    },
    {
      id: 'empathize',
      label: 'Empathize',
      blocks: [
        h('Research Goals'),
        cards(
          [
            { kicker: 'GOAL 1', title: 'Map the journey', html: 'Document the end-to-end NMLS licensing journey of 6 core workflows for small-company users.' },
            { kicker: 'GOAL 2', title: 'Locate friction', html: 'Identify high error touchpoints, especially where users turn to the Resource Center or call support.' },
            { kicker: 'GOAL 3', title: 'Assess RC perception', html: 'Evaluate findability, completeness, and trust in the current Resource Center vs. users’ expectations.' },
          ],
          { cols: 3, variant: 'plain' },
        ),
        h('Methods'),
        stats([
          ['6', 'call center interviews'],
          ['3', 'end-user interviews'],
          ['900', 'ServiceNow ticket analysis'],
        ]),
        h('Call Center Interviews'),
        lede('We created a journey map from self-evaluation to guide 6 interviews with call-center agents.'),
        p('I began with a hypothesis journey map from a self-guided system review, then <strong>led six remote, semi-structured 1:1 interviews</strong> (60–90 minutes) with call center agents who understood the licensing process and its pitfalls inside out.'),
        img('7m5JHk73DfwwI2jxSs9vAwsRCmk.jpg', { caption: 'Led call-centre agent interviews using a custom Excel guide outlining key steps across six core workflows' }),
        h('User Interviews'),
        p('Then, we <strong>led three remote, semi-structured 1:1 interviews</strong> (60–90 minutes) with end-users. This helped us directly empathize with the unique experiences of small company users.'),
        img('SfCuyk9nIVoJIQgwThjEG8zyuVQ.jpg', { caption: 'Interviewing end users to assess RC perception and understand user journey' }),
        h('ServiceNow Analytics'),
        lede('To <mark>quantify findings</mark>, I extracted ServiceNow call-center tickets, analyzing a random sample of 900 (150/workflow) to size pain points against themes.'),
        gallery(['IjZYvkNkj0rsZjAE1UAFgcJGI.png', 'GPyEID7TRoGnv0r6CsAwJ9Sj4J4.jpg'], { cols: 2, caption: 'Extracting tickets from ServiceNow (last 1 month)' }),
      ],
    },
    {
      id: 'define',
      label: 'Define',
      blocks: [
        h('Affinity Mapping and Synthesis'),
        p('Using Miro, I organized all research insights under six key workflow categories. From there, I extracted user pain points and identified over 25 issues that directly informed six journey maps.'),
        img('SrmoZmiKYD7LbLbnidvIN3hP9k.jpg', { caption: 'Affinity mapping to extract user behaviors and pain points', wide: true }),
        h('Key Insights'),
        img('BtJpZVkVUs5knJVbAwHJw1e0w.png', { wide: true }),
        h('User Journey Maps'),
        p('I synthesized research findings into six detailed journey maps, each structured around user actions, emotional journey, quantified pain points, and verbatim quotes. The color-coded data rows highlight issue severity, making it easy for stakeholders to identify where users struggle most.'),
        gallery(['vpdmEyGdI8ImCPy5Q0EiBG0q4.jpg', 'cR6UphDJYrl5KBsgJPeOYdQRZ08.jpg'], { cols: 1, caption: 'A snapshot of the six journey maps created', wide: true }),
      ],
    },
    {
      id: 'ideate',
      label: 'Ideate',
      blocks: [
        h('Design Goals'),
        cards(
          [
            { img: 'W6lJ51HpyHO1FrWLLwi9EbnGZw.png', title: 'Reduce Visual Clutter', html: 'How might we create a clearer, more focused homepage that helps users find what they need?' },
            { img: 'U5HsVUvqaPgpeN7WzWV9AGRSs.png', title: 'Simplify Navigation', html: 'How might we help users locate licensing checklists and key resources faster?' },
            { img: 'vCn90r8rXrabnQKEeG4l9T9hTm8.png', title: 'Improve Search', html: 'How might we help users find specific information without feeling overwhelmed?' },
            { img: 'F85f49n1CfJ5FqLZ64AdBJCHcrk.png', title: 'Clarify Language', html: 'How might we make NMLS terminology accessible to first-time small business users?' },
            { img: 'TPNXAfdyQcQS143SAZLvKNPpds.png', title: 'Keep Content Current', html: 'How might we ensure users always have access to accurate, up-to-date information?' },
          ],
          { cols: 5, variant: 'icon' },
        ),
      ],
    },
    {
      id: 'prototype',
      label: 'Prototype',
      blocks: [
        h('New NMLS Resource Center'),
        lede('The New NMLS Resource Center <mark>launched</mark> on September 20, 2025.'),
        p('The redesigned NMLS Resource Center directly addresses key pain points from our research: confusing navigation, information overload, and content that previously catered only to large companies.'),
        feature({
          n: '01',
          title: 'Task-Based Information Architecture',
          items: ['Removed competing content sections like NMLS News, Agency News, and Popular Links.', 'Persistent sidebar navigation.', 'Reduced cognitive load and resources organized by user type and task.'],
          media: ['BXlkhlt8LeADLUGEYUTiZB2xs54.jpg'],
        }),
        feature({
          n: '02',
          title: 'Global Persistent Search',
          items: ['Persistent, prominent search bar accessible from every page.', 'Contextual search within sections allows users to search within their current area for more relevant results.'],
          media: ['cytCJG0dDu98YnBOtMXYOqHYTo.jpg'],
          flip: true,
        }),
        feature({
          n: '03',
          title: 'Dynamic Content Management',
          items: ['Replaced static PDFs with XML-based content.', 'Content editors can push changes instantly without regenerating and re-uploading entire documents.', 'Broken links, duplicates, and outdated pages are gone.'],
          media: ['a9Ks6XtxlvRgtDf1JChl7LQakk.png'],
        }),
        feature({
          n: '04',
          title: 'Integrated Glossary Access',
          items: ['NMLS Glossary surfaced on homepage as well as internal sections, previously buried deep in documentation.', 'Glossary sits alongside related policy content, so users can reference terms while completing tasks.'],
          media: ['GSYkrkshJsH7cULPBcUm93qbcM.png'],
          flip: true,
        }),
      ],
    },
    {
      id: 'reflection',
      label: 'Reflection',
      blocks: [
        h('Impact'),
        cards(
          [
            { title: 'Visibility', html: 'Synthesized and presented user research to VPs and Product Managers, bridging the gap between user insights and strategic product decisions.' },
            { title: 'Validation', html: 'Socialized the redesigned Resource Center with call center teams (the same users who informed our research) resulting in strong positive reception.' },
            { title: 'UX perception', html: 'Helped establish UX credibility within the business unit, showcasing how research-driven design leads to measurable product improvements.' },
          ],
          { cols: 3, variant: 'numbered' },
        ),
        h('Impact Stats'),
        stats([
          ['50%', 'reduction in navigation time across 10 common searches'],
          ['~ 600 K', 'industry users impacted (state and federal Resource Center)'],
          ['6', 'journey maps delivered, covering the most critical licensing workflows'],
        ]),
        h('Reflection'),
        p('I completed my internship in August 2025 and was extended through the Fall semester. Working at the intersection of financial regulation and UX has taught me more than I can easily summarize, but here are the key takeaways:'),
        list([
          '<strong>Empathy is key: </strong>Conducting user interviews revealed just how much is at stake in this industry. Every piece of instructional text, every button placement carries weight that can cost people their livelihoods. Designing with user empathy has never felt more essential.',
          '<strong>Data drives buy in, but stories create connection:</strong> Senior stakeholders need the numbers, user counts, error rates, conversion metrics. But user stories are what make those numbers resonate. Learning to weave both qualitative and quantitative methods into my journey maps has been one of the most rewarding parts of this work.',
          '<strong>Pivot often: </strong>Real-world projects are rarely linear. We started with a vague goal of improving self-service for small company users, paused, and shifted to understanding their pain points. That detour uncovered insights that shaped key decisions and informed tree testing for the new NMLS Resource Center information architecture.',
          "<strong>Small discoveries snowball: </strong>This research also helped us improve support for call center agents. A deep dive into ServiceNow call center data revealed untapped potential for UX improvements we hadn't anticipated.",
        ], true),
        gallery(['acRAcPK51NoLJ8LHSqgrpjj2Wg.jpeg', '0DgrhSrnYqbmgZKu3PnA8Rrtvw.jpeg', 'pIDtD36Hpq3doMGXAW2oSsLaNgE.jpeg', 'NfKXubAUMyPGvUNfxwNhQaPIR7c.png'], { cols: 2 }),
      ],
    },
  ],
};

export default cs;
