/**
 * revcloud.ts · WP4a. The revision cloud around her "Update" callout (SPEC SM6b).
 *
 *  1. Take the callout's border box, outset by 10px (6px on phones, so the scallops stay inside the 16px margin).
 *  2. Walk the perimeter clockwise from the top-left corner. Each side is divided into n = max(2, round(len / 26))
 *     segments (len / 22 on phones: tighter scallops).
 *  3. Each segment is an SVG arc `A r r 0 0 1 x y`, r = segLen · 0.62, which bulges OUTWARD on a clockwise walk.
 *     r gets ±6% jitter from a PRNG seeded by the element id: it looks hand-drawn and is identical on every visit.
 *  4. pathLength="1": the stroke draws once (stroke-dashoffset 1 → 0 over --dur-6, --ease-draft) when ≥ 40% of the
 *     callout is visible; the blush fill fades in behind the pen, starting --dur-6/4 later.
 *  5. Motion off / reduced motion: drawn statically. A fast scroll (> 3 viewports/s) completes it instantly (§2.7 law 5).
 *  The path is regenerated by a ResizeObserver, so it re-flows with the text. Without JS the callout keeps its plain
 *  ruled box (CSS), and print always shows the finished cloud.
 */
import { motionOK } from '../core/dom';
import { on as onPref } from '../core/prefs';

/** FNV-1a: a stable 32-bit seed from the element id. */
function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** mulberry32: a tiny deterministic PRNG in [0, 1). */
function prng(seed: number): () => number {
  let a = seed | 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const f = (n: number) => Math.round(n * 100) / 100;

export interface CloudOpts {
  /** how far outside the border box the cloud runs (px) */
  outset: number;
  /** target segment length (px): 26 on desktop, 22 on phones */
  seg: number;
  /** seed string (the element id) */
  seed: string;
  /** radius as a fraction of the segment length */
  bulge?: number;
  /** ± jitter of the radius */
  jitter?: number;
}

/** The scalloped perimeter of a w × h box, in the box's own coordinates (the path runs outside it). */
export function cloudPath(w: number, h: number, o: CloudOpts): string {
  const bulge = o.bulge ?? 0.62;
  const jitter = o.jitter ?? 0.06;
  const rnd = prng(hash(o.seed));
  const x0 = -o.outset, y0 = -o.outset, x1 = w + o.outset, y1 = h + o.outset;
  const corners: [number, number][] = [[x0, y0], [x1, y0], [x1, y1], [x0, y1]];
  let d = `M${f(x0)} ${f(y0)}`;
  for (let s = 0; s < 4; s++) {
    const [ax, ay] = corners[s];
    const [bx, by] = corners[(s + 1) % 4];
    const len = Math.hypot(bx - ax, by - ay);
    const n = Math.max(2, Math.round(len / o.seg));
    const segLen = len / n;
    for (let i = 1; i <= n; i++) {
      const x = ax + ((bx - ax) * i) / n;
      const y = ay + ((by - ay) * i) / n;
      const r = segLen * bulge * (1 + (rnd() * 2 - 1) * jitter);
      d += `A${f(r)} ${f(r)} 0 0 1 ${f(x)} ${f(y)}`;
    }
  }
  return `${d}Z`;
}

const PHONE = '(max-width: 767.98px)';

/** Fast-scroll bypass: true while the page scrolls faster than 3 viewports per second. */
let lastY = 0;
let lastT = 0;
let fast = false;
function trackVelocity(): () => void {
  lastY = scrollY;
  lastT = performance.now();
  const onScroll = () => {
    const t = performance.now();
    const dt = t - lastT;
    if (dt > 0) fast = (Math.abs(scrollY - lastY) / innerHeight) / (dt / 1000) > 3;
    lastY = scrollY;
    lastT = t;
  };
  addEventListener('scroll', onScroll, { passive: true });
  return () => removeEventListener('scroll', onScroll);
}

function init(el: HTMLElement, pending: Set<HTMLElement>, done: () => void): void {
  const line = el.querySelector<SVGPathElement>('.rev__line');
  const fill = el.querySelector<SVGPathElement>('.rev__fill');
  if (!line || !fill) return;
  const seed = el.dataset.seed || el.id || 'rev';
  const phone = matchMedia(PHONE);
  let w = 0;
  let h = 0;
  const render = () => {
    const nw = el.offsetWidth;
    const nh = el.offsetHeight;
    if (!nw || !nh || (nw === w && nh === h)) return;
    w = nw;
    h = nh;
    const d = cloudPath(w, h, { outset: phone.matches ? 6 : 10, seg: phone.matches ? 22 : 26, seed });
    line.setAttribute('d', d);
    fill.setAttribute('d', d);
  };
  render();
  new ResizeObserver(render).observe(el);
  phone.addEventListener('change', () => { w = 0; render(); });
  el.classList.add('has-cloud');

  if (!motionOK()) { el.classList.add('is-drawn', 'is-static'); return; }
  el.classList.add('is-pending');
  pending.add(el);
  // one element, one native observer (the core/io pool is for shared targets; this keeps the cloud ≤ 1.5 KB gz)
  const io = new IntersectionObserver(([en]) => {
    if (!en.isIntersecting || en.intersectionRatio < 0.4) return;
    io.disconnect();
    if (!pending.has(el)) return;
    pending.delete(el);
    if (!pending.size) done();
    if (fast || !motionOK()) el.classList.add('is-static');
    // next frame: the pending state has painted, so the transition runs from dashoffset 1
    requestAnimationFrame(() => {
      el.classList.remove('is-pending');
      el.classList.add('is-drawn');
    });
  }, { threshold: 0.4 });
  io.observe(el);
}

export function initRevClouds(root: ParentNode = document): void {
  const els = Array.from(root.querySelectorAll<HTMLElement>('[data-revcloud]'));
  if (!els.length) return;
  const pending = new Set<HTMLElement>();
  const stop = trackVelocity();
  for (const el of els) init(el, pending, stop);
  if (!pending.size) { stop(); return; }
  // Motion switched off mid-visit: finish every pending cloud at once
  const off = onPref('motion', (v) => {
    if (v !== 'reduce') return;
    for (const el of pending) {
      el.classList.remove('is-pending');
      el.classList.add('is-drawn', 'is-static');
    }
    pending.clear();
    stop();
    off();
  });
}
